### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by obideuce** [erichiller/motorola_modem_monitor#1]
I'm able to build this docker with no issues. However, when executing, I'm getting the following error in the error logs:

```Successfully connected to host 192.168.100.1 at https://192.168.100.1:443/HNAP1/
Traceback (most recent call last):
  File ".\motorola_cable.py", line 371, in <module>
    modem = MotorolaModem("192.168.100.1", "motorola", "admin")
  File ".\motorola_cable.py", line 83, in __init__
    self.getStatus()
  File ".\motorola_cable.py", line 87, in getStatus
    self.status = self.Action(Action="GetMultipleHNAPs", responseElement="", params = "")
  File ".\motorola_cable.py", line 187, in Action
    self.authenticated = self.auth()
  File ".\motorola_cable.py", line 290, in auth
    ChallengeResponse = json_response["Challenge"]
KeyError: 'Challenge' 
```

Any ideas on what needs to be done to correct this?

**Comment by obideuce** [comment]
This eventually just corrected itself.

**Comment by erichiller** [comment]
I had a similar problem a bit ago when Comcast pushed a firmware update. glad it's going now.
